name: books_wallah
version: 1.0.4+4
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  new_version: ^0.3.1
  wakelock: ^0.6.2
  path_provider: ^2.0.11
  intl: ^0.17.0
  share_plus: ^4.0.10
  url_launcher: ^6.1.5
  app_settings: ^4.1.8
  intl_phone_field: ^3.1.0
  alh_pdf_view: ^0.3.3
  get_storage: ^2.0.3
  http: ^0.13.4
  auto_size_text: ^3.0.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
